=== sammerDib/Demeter-Test/PM/DEMETER/Service/UnitySC.PM.DMT.Service.Host/bin/4VIS2267/Configuration/UserRights/AccessRights.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by Saint (EMBRACE) -->
<!-- edited with XML Spy v4.0.1 U (http://www.xmlspy.com) by Romanovskaya (Mecasoft) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="AccessRights" type="AccessRightsType">
    <xs:annotation>
      <xs:documentation>Comment describing your root element</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:complexType name="AccessRightsType">
    <xs:sequence>
      <xs:element name="NavigationRights" type="NavigationRightsType">
        <xs:unique name="NavigationNameUnique">
          <xs:selector xpath="./*"/>
          <xs:field xpath="Name"/>
        </xs:unique>
      </xs:element>
      <xs:element name="ProcessProgramRights" type="ProcessProgramRightsType">
        <xs:unique name="ProcessProgramGroupUnique">
          <xs:selector xpath="./*"/>
          <xs:field xpath="Name"/>
        </xs:unique>
      </xs:element>
      <xs:element name="LogonDialogRights" type="RightType"/>
      <xs:element name="Users" type="UsersType">
        <xs:unique name="UserNameUnique">
          <xs:selector xpath="./*"/>
          <xs:field xpath="Name"/>
        </xs:unique>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="NavigationRightsType">
    <xs:sequence>
      <xs:element name="NavigationArea" type="NavigationAreaType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SubNavigationRightsType">
    <xs:sequence>
      <xs:element name="SubNavigation" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Level">
              <xs:simpleType>
                <xs:restriction base="xs:int">
                  <xs:enumeration value="0"/>
                  <xs:enumeration value="1"/>
                  <xs:enumeration value="2"/>
                  <xs:enumeration value="3"/>
                  <xs:enumeration value="4"/>
                  <xs:enumeration value="5"/>
                  <xs:enumeration value="6"/>
                  <xs:enumeration value="7"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:element>
            <xs:element name="InformationPanelRights" type="RightType" minOccurs="0">
              <xs:unique name="InfoElementName">
                <xs:selector xpath="./*"/>
                <xs:field xpath="Name"/>
              </xs:unique>
            </xs:element>
            <xs:element name="CommandPanelRights" type="RightType" minOccurs="0">
              <xs:unique name="CommandBtnName">
                <xs:selector xpath="./*"/>
                <xs:field xpath="Name"/>
              </xs:unique>
            </xs:element>
            <xs:element name="DialogBoxRights" type="RightType" minOccurs="0">
              <xs:unique name="DialogElementName">
                <xs:selector xpath="./*"/>
                <xs:field xpath="Name"/>
              </xs:unique>
            </xs:element>
			<xs:element name="ToolBoxRights" type="RightType" minOccurs="0">
              <xs:unique name="ToolElementName">
                <xs:selector xpath="./*"/>
                <xs:field xpath="Name"/>
              </xs:unique>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ProcessProgramRightsType">
    <xs:sequence>
      <xs:element name="Group" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Level">
              <xs:simpleType>
                <xs:restriction base="xs:int">
                  <xs:enumeration value="0"/>
                  <xs:enumeration value="1"/>
                  <xs:enumeration value="2"/>
                  <xs:enumeration value="3"/>
                  <xs:enumeration value="4"/>
                  <xs:enumeration value="5"/>
                  <xs:enumeration value="6"/>
                  <xs:enumeration value="7"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="UsersType">
    <xs:sequence>
      <xs:element name="User" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Password" type="xs:string"/>
            <xs:element name="Level">
              <xs:simpleType>
                <xs:restriction base="xs:int">
                  <xs:enumeration value="0"/>
                  <xs:enumeration value="1"/>
                  <xs:enumeration value="2"/>
                  <xs:enumeration value="3"/>
                  <xs:enumeration value="4"/>
                  <xs:enumeration value="5"/>
                  <xs:enumeration value="6"/>
                  <xs:enumeration value="7"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="RightType">
    <xs:sequence>
      <xs:element name="Right" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Level">
              <xs:simpleType>
                <xs:restriction base="xs:int">
                  <xs:enumeration value="0"/>
                  <xs:enumeration value="1"/>
                  <xs:enumeration value="2"/>
                  <xs:enumeration value="3"/>
                  <xs:enumeration value="4"/>
                  <xs:enumeration value="5"/>
                  <xs:enumeration value="6"/>
                  <xs:enumeration value="7"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="NavigationAreaType">
    <xs:sequence>
      <xs:element name="Name" type="xs:string"/>
      <xs:element name="Level">
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:enumeration value="0"/>
            <xs:enumeration value="1"/>
            <xs:enumeration value="2"/>
            <xs:enumeration value="3"/>
            <xs:enumeration value="4"/>
            <xs:enumeration value="5"/>
            <xs:enumeration value="6"/>
            <xs:enumeration value="7"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="SubNavigationRights" type="SubNavigationRightsType" minOccurs="0" maxOccurs="1">
        <xs:unique name="SubNavigationNameUnique">
          <xs:selector xpath="./*"/>
          <xs:field xpath="Name"/>
        </xs:unique>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== sammerDib/Demeter-Test/UTO/src/UnitySC.UTO.Controller/Configuration/XML/AccessRights.xml
<?xml version="1.0"?>
<AccessRights xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\Configuration\XSD\AccessRights.xsd">
  <NavigationRights>
    <NavigationArea>
      <Name>Root.ROOT_SETUP.PROCESS.BP_SCENARIOS.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_SETUP.PROCESS.BP_SCENARIOS_CONFIGURATION.SETUP_GROUPS_DEFINITION_EDIT_SCENARIO_GROUP.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_ALARMS.ALARMS_HISTORY.ALARMS_RELOAD.IsEnabled</Name>
      <Level>3</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_MAIN.ROOT_MAIN_EQUIPMENT.EQUIPMENT_RESET.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_SETUP.MENU_APPLICATION.BP_ACCESSRIGHTS.S_SETUP_ACCESSRIGHTS_RESTORE.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_MAIN.ROOT_MAIN_EQUIPMENT.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_MAINTENANCE.BP_SCENARIO_MANAGER.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_MAIN.ROOT_MAIN_EQUIPMENT.EQUIPMENT_ABORT.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>TITLE_PANEL_CONTROL_COMMAND.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_LOGS.TRACE VIEWER.S_DATALOG_TRACES_CLEARALL.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_SETUP.PROCESS.BP_PROCESS_PROGRAM_CONFIG.SETUP_GROUPS_DEFINITION_DELETE_RECIPE_GROUP.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>SETUP_UNDO_CHANGES_COMMAND.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_ALARMS.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_SETUP.PROCESS.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_RECIPES.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_SETUP.PROCESS.BP_SCENARIOS_CONFIGURATION.SETUP_GROUPS_DEFINITION_ADD_SCENARIO_GROUP.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>ToolManager.RapidColor.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_MAIN.ROOT_MAIN_EQUIPMENT.ResetCommand.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_MAINTENANCE.BP_SCENARIO_SEQUENCER.SCENARIO_EXECUTION_CONFIGURATION.UncheckedCommand.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_DIAGNOSTICS.TRACEVIEWER_SCROLL_TO_END.CheckedCommand.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_GEM.MENU_GEM_DATA_DICTIONARY.GEMPANELS_DATA_VARIABLES.GEMPANELS_REFRESH.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_DIAGNOSTICS.TRACEVIEWER_SCROLL_TO_END.UncheckedCommand.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_GEM.GEM_JOBSMENU.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_HELP.MENU_DEVELOPERS.BP_SAMPLE.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_SETUP.PROCESS.BP_SCENARIOS_CONFIGURATION.SETUP_GROUPS_DEFINITION_ADD_SCENARIO_GROUP.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_SETUP.MENU_APPLICATION.ROOT_ALARMS.SAVE_COMMAND.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_MAINTENANCE.BP_COMMUNICATION_VISUALIZER.TRACEVIEWER_SCROLL_TO_END.UncheckedCommand.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_MAINTENANCE.BP_COMMUNICATION_VISUALIZER.TRACEVIEWER_SCROLL_TO_END.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_LOGS.DATALOG.S_DATALOG_TRACES_CLEARALL.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_ALARMS.BP_ALARM_ANALYSIS.ALARM_ANALYSIS_RELOAD.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_GEM.GEM_JOBSMENU.CJ_HOQ.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_TRACES.TRACEVIEWER_PAUSE_RESUME.TRACEVIEWER_PAUSE.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_LOGS.Old DATALOG.S_DATALOG_FILTER_APPLY.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_SETUP.MENU_APPLICATION.BP_ACCESSRIGHTS.SAVE_COMMAND.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_MAINTENANCE.BP_SAMPLE.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_RECIPES.BP_RECIPE_LIBRARY.Edit.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_GEM.BP_CARRIERS.CARRIERS_EDIT.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
	<NavigationArea>
		<Name>Root.ROOT_MAIN.ROOT_MAIN_EQUIPMENT.EQUIPMENT_PM_ABORT_RECIPE.IsVisible</Name>
		<Level>0</Level>
	</NavigationArea>
	<NavigationArea>
		<Name>Root.ROOT_MAIN.ROOT_MAIN_EQUIPMENT.EQUIPMENT_PM_ABORT_RECIPE.IsEnabled</Name>
		<Level>3</Level>
	</NavigationArea>
    <NavigationArea>
      <Name>Root.BP_PROCESS.DATAFLOW_ENGINEERING_MODE.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_SETUP.Process.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_MAIN.ROOT_MAIN_PRODUCTION.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_LOGS.S_DATALOG_TRACES_CLEARALL.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.BP_RESULTS.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_MAIN.ROOT_MAIN_EQUIPMENT.EQUIPMENT_ABORT.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_LOGS.DATALOG.S_DATALOG_TRACES_PAUSE_RESUME.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_HELP.MENU_DEVELOPERS.BP_SAMPLE.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_SETUP.MENU_APPLICATION.BP_ACCESSRIGHTS.SAVE_COMMAND.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_SETUP.MENU_APPLICATION.BP_APP_CONFIG.UNDO_COMMAND.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_GEM.GEM_JOBSMENU.GEM_PAUSE.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_SETUP.MENU_APPLICATION.BP_ACCESSRIGHTS.UNDO_COMMAND.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_GEM.BP_CARRIERS.CARRIERS_RECREATE.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_GEM.SUB_TRACK.SUB_TRACK_COMPARE.CheckedCommand.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_MAINTENANCE.BP_EQUIPMENT_HANDLING.EQUIPMENT_LOAD_PM.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_MAINTENANCE.BP_SCENARIO_LIBRARY.SETUP_SAVE_CONFIG_COMMAND.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_HELP.MENU_DEVELOPERS.MENU_GUI_COMPONENTS.BP_NAVIGATION.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_GEM.SUB_TRACK.SUB_TRACK_COMPARE.CheckedCommand.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_MAIN.ROOT_MAIN_PRODUCTION.RUN_PROG_CMD.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_MAINTENANCE.BP_COMMUNICATION_VISUALIZER.TRACEVIEWER_SCROLL_TO_END.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>TITLE_PANEL_EQUIPMENT_COMMAND.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_LOGS.S_DATALOG_TRACES_PAUSE_RESUME.S_DATALOG_TRACES_PAUSE.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_GEM.GEMPANELS_STATUS_VARIABLES.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_GEM.BP_SMN_VIEWER.SEQUENCE_LOG_CLEAR.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_GEM.GEM_JOBSMENU.GEM_ADD_JOB.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_SETUP.Process.BP_PROCESS_PROGRAM_CONFIG.IsVisible</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
      <Name>Root.ROOT_GEM.BP_LOADPORTS_OVERVIEW.CARRIERS_CANCEL_RESERVATION.IsEnabled</Name>
      <Level>0</Level>
    </NavigationArea>
    <NavigationArea>
