=== sammerDib/Demeter-Test/UTO/src/UnitySC.UTO.Controller/Configuration/XSD/MessagesConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.0.1 U (http://www.xmlspy.com) by Irisha (home) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="Data">
    <xs:annotation>
      <xs:documentation>Comment describing your root element</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="HostConfig"/>
        <xs:element ref="Secs2DataItems"/>
        <xs:element ref="Variables"/>
        <xs:element ref="Reports"/>
        <xs:element ref="CollectionEvents"/>
        <xs:element ref="CommunicationPiping"/>
        <xs:element ref="Alarms"/>
        <xs:element name="LimitsMonitoring" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="MonitoringVar" type="VarLimits" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="HostConfig">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="HostCommonConfig" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="HC" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="VID" type="xs:string"/>
                    <xs:element name="VName" type="xs:string"/>
                    <xs:element name="Value"/>
                    <xs:element name="Units"/>
                    <xs:element name="Type">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="B"/>
                          <xs:enumeration value="BOOL"/>
                          <xs:enumeration value="A"/>
                          <xs:enumeration value="I8"/>
                          <xs:enumeration value="I1"/>
                          <xs:enumeration value="I2"/>
                          <xs:enumeration value="I4"/>
                          <xs:enumeration value="F8"/>
                          <xs:enumeration value="F4"/>
                          <xs:enumeration value="U8"/>
                          <xs:enumeration value="U1"/>
                          <xs:enumeration value="U2"/>
                          <xs:enumeration value="U4"/>
                          <xs:enumeration value="L"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="Min"/>
                    <xs:element name="Max"/>
                    <xs:element name="WellKnowName" type="xs:string" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="HostHSMSConfig" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="HC" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="VID" type="xs:string"/>
                    <xs:element name="VName" type="xs:string"/>
                    <xs:element name="Value"/>
                    <xs:element name="Units"/>
                    <xs:element name="Type">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="B"/>
                          <xs:enumeration value="BOOL"/>
                          <xs:enumeration value="A"/>
                          <xs:enumeration value="I8"/>
                          <xs:enumeration value="I1"/>
                          <xs:enumeration value="I2"/>
                          <xs:enumeration value="I4"/>
                          <xs:enumeration value="F8"/>
                          <xs:enumeration value="F4"/>
                          <xs:enumeration value="U8"/>
                          <xs:enumeration value="U1"/>
                          <xs:enumeration value="U2"/>
                          <xs:enumeration value="U4"/>
                          <xs:enumeration value="L"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="Min"/>
                    <xs:element name="Max"/>
                    <xs:element name="WellKnowName" type="xs:string" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="HostSECS1Config" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="HC" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="VID" type="xs:string"/>
                    <xs:element name="VName" type="xs:string"/>
                    <xs:element name="Value"/>
                    <xs:element name="Units"/>
                    <xs:element name="Type">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="B"/>
                          <xs:enumeration value="BOOL"/>
                          <xs:enumeration value="A"/>
                          <xs:enumeration value="I8"/>
                          <xs:enumeration value="I1"/>
                          <xs:enumeration value="I2"/>
                          <xs:enumeration value="I4"/>
                          <xs:enumeration value="F8"/>
                          <xs:enumeration value="F4"/>
                          <xs:enumeration value="U8"/>
                          <xs:enumeration value="U1"/>
                          <xs:enumeration value="U2"/>
                          <xs:enumeration value="U4"/>
                          <xs:enumeration value="L"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="Min"/>
                    <xs:element name="Max"/>
                    <xs:element name="WellKnowName" type="xs:string" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Secs2DataItems">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Secs2DataItem" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" type="xs:string"/>
              <xs:element name="Type">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="B"/>
                    <xs:enumeration value="BOOL"/>
                    <xs:enumeration value="A"/>
                    <xs:enumeration value="I8"/>
                    <xs:enumeration value="I1"/>
                    <xs:enumeration value="I2"/>
                    <xs:enumeration value="I4"/>
                    <xs:enumeration value="F8"/>
                    <xs:enumeration value="F4"/>
                    <xs:enumeration value="U8"/>
                    <xs:enumeration value="U1"/>
                    <xs:enumeration value="U2"/>
                    <xs:enumeration value="U4"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Variables">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="SV" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="VID" type="xs:string"/>
              <xs:element name="VName" type="xs:string"/>
              <xs:element name="Units"/>
              <xs:element name="Type">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="B"/>
                    <xs:enumeration value="BOOL"/>
                    <xs:enumeration value="A"/>
                    <xs:enumeration value="I8"/>
                    <xs:enumeration value="I1"/>
                    <xs:enumeration value="I2"/>
                    <xs:enumeration value="I4"/>
                    <xs:enumeration value="F8"/>
                    <xs:enumeration value="F4"/>
                    <xs:enumeration value="U8"/>
                    <xs:enumeration value="U1"/>
                    <xs:enumeration value="U2"/>
                    <xs:enumeration value="U4"/>
                    <xs:enumeration value="L"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="CEID" type="xs:string" minOccurs="0"/>
              <xs:element name="WellKnowName" type="xs:string" minOccurs="0"/>
		      <xs:element name="Description" type="xs:string" minOccurs="0" />															  
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="DV" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="VID" type="xs:string"/>
              <xs:element name="VName" type="xs:string"/>
              <xs:element name="Units" minOccurs="0" maxOccurs="1"/>
              <xs:element name="Type">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="B"/>
                    <xs:enumeration value="BOOL"/>
                    <xs:enumeration value="A"/>
                    <xs:enumeration value="I8"/>
                    <xs:enumeration value="I1"/>
                    <xs:enumeration value="I2"/>
                    <xs:enumeration value="I4"/>
                    <xs:enumeration value="F8"/>
                    <xs:enumeration value="F4"/>
                    <xs:enumeration value="U8"/>
                    <xs:enumeration value="U1"/>
                    <xs:enumeration value="U2"/>
                    <xs:enumeration value="U4"/>
                    <xs:enumeration value="L"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="WellKnowName" type="xs:string" minOccurs="0"/>
			  <xs:element name="Description" type="xs:string" minOccurs="0" />															  
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="EC" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="VID" type="xs:string"/>
              <xs:element name="VName" type="xs:string"/>
              <xs:element name="Value"/>
              <xs:element name="Units"/>
              <xs:element name="Type">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="B"/>
                    <xs:enumeration value="BOOL"/>
                    <xs:enumeration value="A"/>
                    <xs:enumeration value="I8"/>
                    <xs:enumeration value="I1"/>
                    <xs:enumeration value="I2"/>
                    <xs:enumeration value="I4"/>
                    <xs:enumeration value="F8"/>
                    <xs:enumeration value="F4"/>
                    <xs:enumeration value="U8"/>
                    <xs:enumeration value="U1"/>
                    <xs:enumeration value="U2"/>
                    <xs:enumeration value="U4"/>
                    <xs:enumeration value="L"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Min"/>
              <xs:element name="Max"/>
              <xs:element name="WellKnowName" type="xs:string" minOccurs="0"/>
              <xs:element name="Description" type="xs:string" minOccurs="0" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Reports">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Report" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="RPTID" type="xs:string"/>
              <xs:element name="RPTName" type="xs:string"/>
              <xs:element name="VIDs">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="VID" type="xs:string" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="CollectionEvents">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="CollectionEvent" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="CEID" type="xs:string"/>
              <xs:element name="CEName" type="xs:string"/>
              <xs:element name="Enabled" type="xs:boolean"/>
              <xs:element name="RPTIDs">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="RPTID" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="WellKnowName" type="xs:string" minOccurs="0"/>
              <xs:element name="ValidDVIDs" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="ValidDVID" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="CommunicationPiping">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="IsAllowedOut">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="Messages"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="IsAllowedIn">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="Messages"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Messages">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Message" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Stream" type="xs:byte"/>
              <xs:element name="Function" type="xs:byte"/>
              <xs:element ref="ControlStates"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="ControlStateType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="HostOffLine"/>
      <xs:enumeration value="AttemptOnLine"/>
      <xs:enumeration value="EquipmentOffLine"/>
      <xs:enumeration value="Local"/>
      <xs:enumeration value="Remote"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="ControlStates">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ControlState" type="ControlStateType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Alarms">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Alarm" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ALID"/>
              <xs:element name="ALCD"/>
              <xs:element name="ALTX"/>
              <xs:element name="ALName"/>
              <xs:element name="Enabled" type="xs:boolean"/>
              <xs:element name="SetCEID"/>
              <xs:element name="ClearCEID"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="Limit">
    <xs:sequence>
      <xs:element name="ID" type="xs:string"/>
      <xs:element name="UpperBound" type="xs:string"/>
      <xs:element name="LowerBound" type="xs:string"/>
      <xs:element name="IsEnabled" type="xs:boolean"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="VarLimits">
    <xs:sequence maxOccurs="unbounded">
      <xs:element name="VID" type="xs:string"/>
      <xs:element name="Limit" type="Limit" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== sammerDib/Demeter-Test/UTO/src/UnitySC.DataFlow.ProcessModules/Devices/ProcessModule/Demeter/Resources/MessagesConfiguration.xml
<?xml version="1.0" encoding="utf-8"?>
<Data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./XSD/MessagesConfiguration.xsd">
  <HostConfig>
    <HostCommonConfig>
      <HC>
        <VID>5000</VID>
        <VName>IsHsmsSecsTracerActive</VName>
        <Value>True</Value>
        <Units />
        <Type>BOOL</Type>
        <Min />
        <Max />
        <WellKnowName>IsHsmsSecsTracerActive</WellKnowName>
      </HC>
      <HC>
        <VID>5001</VID>
        <VName>LogFileName</VName>
        <Value>SecsIILog</Value>
        <Units />
        <Type>A</Type>
        <Min />
        <Max />
        <WellKnowName>LogFileName</WellKnowName>
      </HC>
      <HC>
        <VID>5002</VID>
        <VName>LogFileSize</VName>
        <Value>10000000</Value>
        <Units />
        <Type>U8</Type>
        <Min>10000</Min>
        <Max>99999999</Max>
        <WellKnowName>LogFileSize</WellKnowName>
      </HC>
      <HC>
        <VID>5003</VID>
        <VName>LogMode</VName>
        <Value>All</Value>
        <Units />
        <Type>A</Type>
        <Min />
        <Max />
        <WellKnowName>LogMode</WellKnowName>
      </HC>
      <HC>
        <VID>5004</VID>
        <VName>CommunicationType</VName>
        <Value>HSMS</Value>
        <Units />
        <Type>A</Type>
        <Min />
        <Max />
        <WellKnowName>CommunicationType</WellKnowName>
      </HC>
      <HC>
        <VID>5005</VID>
        <VName>DeviceID</VName>
        <Value>10</Value>
        <Units />
        <Type>U2</Type>
        <Min>1</Min>
        <Max>32767</Max>
        <WellKnowName>DeviceID</WellKnowName>
      </HC>
    </HostCommonConfig>
    <HostHSMSConfig>
      <HC>
        <VID>5006</VID>
        <VName>LocalIP</VName>
        <Value>127.0.0.1</Value>
        <Units />
        <Type>A</Type>
        <Min />
        <Max />
        <WellKnowName>LocalIP</WellKnowName>
      </HC>
      <HC>
        <VID>5007</VID>
        <VName>RemoteIP</VName>
        <Value>127.0.0.1</Value>
        <Units />
        <Type>A</Type>
        <Min />
        <Max />
        <WellKnowName>RemoteIP</WellKnowName>
      </HC>
      <HC>
        <VID>5008</VID>
        <VName>LocalTCPPort</VName>
        <Value>5050</Value>
        <Units />
        <Type>U2</Type>
        <Min />
        <Max />
        <WellKnowName>LocalTCPPort</WellKnowName>
      </HC>
      <HC>
        <VID>5009</VID>
        <VName>RemoteTCPPort</VName>
        <Value>5050</Value>
        <Units />
        <Type>U2</Type>
        <Min />
        <Max />
        <WellKnowName>RemoteTCPPort</WellKnowName>
      </HC>
      <HC>
        <VID>5010</VID>
        <VName>IsActive</VName>
        <Value>False</Value>
        <Units />
        <Type>BOOL</Type>
        <Min />
        <Max />
        <WellKnowName>IsActive</WellKnowName>
      </HC>
      <HC>
        <VID>5011</VID>
        <VName>T3</VName>
        <Value>45</Value>
        <Units>s</Units>
        <Type>U1</Type>
        <Min>1</Min>
        <Max>120</Max>
        <WellKnowName>T3</WellKnowName>
      </HC>
      <HC>
        <VID>5012</VID>
        <VName>T5</VName>
        <Value>10</Value>
        <Units>s</Units>
        <Type>U1</Type>
        <Min>1</Min>
        <Max>240</Max>
        <WellKnowName>T5</WellKnowName>
      </HC>
      <HC>
        <VID>5013</VID>
        <VName>T6</VName>
        <Value>5</Value>
        <Units>s</Units>
        <Type>U1</Type>
        <Min>1</Min>
        <Max>240</Max>
        <WellKnowName>T6</WellKnowName>
      </HC>
      <HC>
        <VID>5014</VID>
        <VName>T7</VName>
        <Value>10</Value>
        <Units>s</Units>
        <Type>U1</Type>
        <Min>1</Min>
        <Max>240</Max>
        <WellKnowName>T7</WellKnowName>
      </HC>
      <HC>
        <VID>5015</VID>
        <VName>T8</VName>
        <Value>5</Value>
        <Units>s</Units>
        <Type>U1</Type>
        <Min>1</Min>
        <Max>120</Max>
        <WellKnowName>T8</WellKnowName>
      </HC>
      <HC>
        <VID>5016</VID>
        <VName>LinkTest</VName>
        <Value>60</Value>
        <Units>s</Units>
        <Type>U1</Type>
        <Min>1</Min>
        <Max>240</Max>
        <WellKnowName>LinkTest</WellKnowName>
      </HC>
    </HostHSMSConfig>
    <HostSECS1Config>
      <HC>
        <VID>10201</VID>
        <VName>EntityBehaviour</VName>
        <Value>0</Value>
        <Units />
        <Type>U1</Type>
        <Min />
        <Max />
        <WellKnowName>EntityBehaviour</WellKnowName>
      </HC>
      <HC>
        <VID>10202</VID>
        <VName>BaudRate</VName>
        <Value>9600</Value>
        <Units />
        <Type>U2</Type>
        <Min>300</Min>
        <Max>9600</Max>
        <WellKnowName>BaudRate</WellKnowName>
      </HC>
      <HC>
        <VID>10203</VID>
        <VName>SerialPort</VName>
        <Value>1</Value>
        <Units />
        <Type>U1</Type>
        <Min />
        <Max />
        <WellKnowName>SerialPort</WellKnowName>
      </HC>
      <HC>
        <VID>10204</VID>
        <VName>T1</VName>
        <Value>500</Value>
        <Units>ms</Units>
        <Type>U2</Type>
        <Min>100</Min>
        <Max>10000</Max>
        <WellKnowName>T1</WellKnowName>
      </HC>
      <HC>
        <VID>10205</VID>
        <VName>T2</VName>
        <Value>10000</Value>
        <Units>ms</Units>
        <Type>U2</Type>
        <Min>200</Min>
        <Max>25000</Max>
        <WellKnowName>T2</WellKnowName>
      </HC>
      <HC>
        <VID>10206</VID>
        <VName>T3Secs1</VName>
        <Value>45000</Value>
        <Units>ms</Units>
        <Type>U4</Type>
        <Min>1000</Min>
        <Max>120000</Max>
        <WellKnowName>T3Secs1</WellKnowName>
      </HC>
      <HC>
        <VID>10207</VID>
        <VName>T4</VName>
        <Value>45000</Value>
        <Units>ms</Units>
        <Type>U4</Type>
        <Min>1000</Min>
        <Max>120000</Max>
        <WellKnowName>T4</WellKnowName>
      </HC>
      <HC>
        <VID>10208</VID>
        <VName>RetryLimit</VName>
        <Value>3</Value>
        <Units />
        <Type>U1</Type>
        <Min>0</Min>
        <Max>31</Max>
        <WellKnowName>RetryLimit</WellKnowName>
      </HC>
    </HostSECS1Config>
  </HostConfig>
  <Secs2DataItems>
    <Secs2DataItem>
      <Name>ALID</Name>
      <Type>U4</Type>
    </Secs2DataItem>
    <Secs2DataItem>
      <Name>CEID</Name>
      <Type>U4</Type>
    </Secs2DataItem>
    <Secs2DataItem>
      <Name>DATAID</Name>
      <Type>U2</Type>
    </Secs2DataItem>
    <Secs2DataItem>
      <Name>DATALENGTH</Name>
      <Type>U4</Type>
    </Secs2DataItem>
    <Secs2DataItem>
      <Name>DSPER</Name>
      <Type>A</Type>
    </Secs2DataItem>
    <Secs2DataItem>
      <Name>ECID</Name>
      <Type>U2</Type>
    </Secs2DataItem>
    <Secs2DataItem>
      <Name>ERRCODE</Name>
      <Type>U4</Type>
    </Secs2DataItem>
    <Secs2DataItem>
      <Name>LIMITID</Name>
      <Type>B</Type>
    </Secs2DataItem>
    <Secs2DataItem>
      <Name>MDLN</Name>
      <Type>A</Type>
    </Secs2DataItem>
    <Secs2DataItem>
      <Name>MF</Name>
      <Type>B</Type>
    </Secs2DataItem>
    <Secs2DataItem>
      <Name>OFLACK</Name>
      <Type>B</Type>
    </Secs2DataItem>
    <Secs2DataItem>
      <Name>ONLACK</Name>
      <Type>B</Type>
    </Secs2DataItem>
    <Secs2DataItem>
      <Name>REPGSZ</Name>
      <Type>U4</Type>
    </Secs2DataItem>
    <Secs2DataItem>
      <Name>RPTID</Name>
      <Type>U2</Type>
    </Secs2DataItem>
    <Secs2DataItem>
      <Name>SMPLN</Name>
      <Type>U4</Type>
    </Secs2DataItem>
    <Secs2DataItem>
      <Name>SOFTREV</Name>
      <Type>A</Type>
    </Secs2DataItem>
    <Secs2DataItem>
      <Name>STIME</Name>
      <Type>A</Type>
    </Secs2DataItem>
    <Secs2DataItem>
      <Name>SVID</Name>
      <Type>U2</Type>
    </Secs2DataItem>
    <Secs2DataItem>
      <Name>TID</Name>
      <Type>B</Type>
    </Secs2DataItem>
    <Secs2DataItem>
      <Name>TOTSMP</Name>
      <Type>U4</Type>
    </Secs2DataItem>
    <Secs2DataItem>
      <Name>TRID</Name>
      <Type>U4</Type>
    </Secs2DataItem>
    <Secs2DataItem>
      <Name>VID</Name>
      <Type>U4</Type>
    </Secs2DataItem>
  </Secs2DataItems>
  <Variables>
    <SV>
      <VID>1010</VID>
      <VName>ProcessModule1State</VName>
      <Units />
      <Type>A</Type>
      <WellKnowName>ProcessModule1State</WellKnowName>
    </SV>
    <SV>
      <VID>1011</VID>
      <VName>ProcessModule1RecipeName</VName>
      <Units />
      <Type>A</Type>
      <WellKnowName>ProcessModule1RecipeName</WellKnowName>
    </SV>
    <SV>
      <VID>1012</VID>
      <VName>ProcessModule1ReadyForProcess</VName>
      <Units />
      <Type>BOOL</Type>
      <WellKnowName>ProcessModule1ReadyForProcess</WellKnowName>
    </SV>
    <SV>
      <VID>1013</VID>
      <VName>ProcessModule1RecipeActive</VName>
      <Units />
      <Type>BOOL</Type>
      <WellKnowName>ProcessModule1RecipeActive</WellKnowName>
    </SV>
    <SV>
      <VID>1014</VID>
      <VName>ProcessModule1TransferState</VName>
      <Units />
      <Type>A</Type>
      <WellKnowName>ProcessModule1TransferState</WellKnowName>
    </SV>
    <SV>
      <VID>1015</VID>
      <VName>ProcessModule1MaterialPresenceState</VName>
      <Units />
      <Type>A</Type>
      <WellKnowName>ProcessModule1MaterialPresenceState</WellKnowName>
    </SV>
    <SV>
      <VID>1016</VID>
      <VName>ProcessModule1PMAcquisitionProgress_Percentage</VName>
      <Units>%</Units>
      <Type>U1</Type>
      <WellKnowName>ProcessModule1PMAcquisitionProgress_Percentage</WellKnowName>
    </SV>
    <SV>
      <VID>1017</VID>
      <VName>ProcessModule1PMComputationProgress_Percentage</VName>
      <Units>%</Units>
      <Type>U1</Type>
      <WellKnowName>ProcessModule1PMComputationProgress_Percentage</WellKnowName>
    </SV>
    <SV>
      <VID>1018</VID>
      <VName>ProcessModule1PMAcquisitionProgress_SubstID</VName>
      <Units />
